### ISSUE TITLE
Add citation file to select repositories

### ISSUE THREAD

**Issue by victorlin** [nextstrain/public#11]
[CFF](https://citation-file-format.github.io) is a file format for citations. Adding one will show a "[Cite this repository](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files)" button on the GitHub repo's homepage. Do this where applicable.

## Tasks

- [x] https://github.com/nextstrain/augur/pull/1700
- [x] https://github.com/nextstrain/auspice/pull/1921
- [x] https://github.com/nextstrain/nextstrain.org/pull/1086

**Comment by victorlin** [comment]
I've added them to Augur, Auspice, and nextstrain.org. Open to suggestions for other repos.
