### ISSUE TITLE
Rollout pandas version 2

### ISSUE THREAD

**Issue by victorlin** [nextstrain/public#12]
Currently, Augur is pinned to pandas version 1:

https://github.com/nextstrain/augur/blob/1694a3fe1f2e4271849120ee08b29cb8286dc1fa/setup.py#L64

There have been numerous requests with good reason to support pandas version 2:

- nextstrain/augur#1303
- nextstrain/augur#1316
- nextstrain/augur#1436
- nextstrain/augur#1471

### Tasks

- [x] Merge https://github.com/nextstrain/augur/pull/1671
- [x] https://github.com/nextstrain/augur/issues/1684
- [ ] Ensure the pins are propagated to conda-base and docker-base
- [ ] Be on the watch for potential unexpected pandas upgrade related changes in our ecosystem
    - fauna ([pinned to v1](https://github.com/nextstrain/fauna/blob/185c02e136f3f0ca6255b350831d8179b0ea1750/requirements.txt#L4), installed via pip in [docker-base before augur](https://github.com/nextstrain/docker-base/blob/abb3f91c2b3d8e01bf01ff137db0cb64ada84285/Dockerfile#L303))
    - ncov-ingest ([pinned to v1](https://github.com/nextstrain/ncov-ingest/blob/c1af4b7e5e956c92e6bac224d6c3d87cf758a46f/requirements.txt#L3), installed via pip in [custom Dockerfile](https://github.com/nextstrain/ncov-ingest/blob/c1af4b7e5e956c92e6bac224d6c3d87cf758a46f/Dockerfile#L42) layered atop docker-base)

**Comment by victorlin** [comment]
evofr supports pandas v2 now, so the bump should happen in the next update of runtimes. Let's rebuild conda-base first to see if CI passes across pathogen repos.

Dependencies on bioconda need to be updated first. Could someone open a PR to bioconda-recipes with this link? https://github.com/nextstrain/bioconda-recipes/pull/new/evofr-0.2.1

**Comment by joverlee521** [comment]
> Dependencies on bioconda need to be updated first. Could someone open a PR to bioconda-recipes with this link? https://github.com/nextstrain/bioconda-recipes/pull/new/evofr-0.2.1

Done: https://github.com/bioconda/bioconda-recipes/pull/66591

**Comment by victorlin** [comment]
I rebuilt conda-base but it still resolved to [evofr 0.2.1 pyhdfd78af_0](https://github.com/nextstrain/conda-base/actions/runs/27975357012/job/82791663283#step:6:433) (old build) and [pandas 1.5.3](https://github.com/nextstrain/conda-base/actions/runs/27975357012/job/82791663283#step:6:378). A [test run](https://github.com/nextstrain/conda-base/actions/runs/27977146295/job/82797720090#step:6:94) with pin to pandas >=2 shows that it's because of pins by the pathogen-embed package.

```
└─ pathogen-embed =* * is not installable because it requires
   └─ pandas >=1.2.0,<2 *, which can be installed.
```

Confusingly, pathogen-embed on PyPI (used by docker-base) does not have such a restriction. See https://github.com/blab/pathogen-embed/issues/27#issuecomment-4772987235

For now, pandas will continue to resolve to v1 in our runtimes, though there is a separate reason for each runtime. I've updated the task list accordingly.

**Comment by joverlee521** [comment]
Re: docker-base/fauna

The only pathogen workflow that uses fauna now should be [seasonal-flu/upload_titers](https://github.com/nextstrain/seasonal-flu/blob/f1fc8b9f6a1e05d4163f1f18f2a3cd716f59edbd/.github/workflows/upload.yaml#L67-L84). I'm very tempted to just pin the image tag for that workflow and just remove fauna from docker-base. However, the titer workflow is currently embedded in the default seasonal-flu workflow, so if we made any updates, then we might get blocked by the pinned image tag. It could be worth the time to pull out the titer processing rules into a completely independent workflow that we never update and pin the image tag. 

Alternatively, we could sidestep the issue and try isolating fauna in it's own venv in docker-base (similar to [what was done for aws-cli v1](https://github.com/nextstrain/docker-base/pull/215))

**Comment by victorlin** [comment]
> Alternatively, we could sidestep the issue and try isolating fauna in it's own venv in docker-base (similar to [what was done for aws-cli v1](https://github.com/nextstrain/docker-base/pull/215))

+1, seems more approachable than the other alternatives.

**Comment by victorlin** [comment]
conda-base now uses pandas v2 as of version 20260701T184946Z ([link to build](https://github.com/nextstrain/conda-base/actions/runs/28540264477)):

```
name: pandas
  version: "1.5.3" => "2.3.3"
```
