### ISSUE TITLE
Deprecation of projects without explicit Sphinx or MkDocs configuration

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/public#15]
From the [email](https://support.nextstrain.org/agent/nextstrain/nextstrain/tickets/details/668036000008556002):

> We are announcing the deprecation of projects using Sphinx or MkDocs without an explicit configuration in their .readthedocs.yaml file. After January 20, 2025, Read the Docs will require explicit configuration for all Sphinx and MkDocs projects.
> 
> We used to automatically try to find the configuration file for your project, but in order to make builds more explicit and predictable, we are deprecating this behavior. This will also allows us to better support projects that don't use Sphinx or MkDocs in the near future.
> What do I need to do?
> 
> If you're using Sphinx or MkDocs, ensure your .readthedocs.yaml file includes the appropriate configuration key. For example:
> 
> For Sphinx projects:
> 
> version: 2
> sphinx:
>   configuration: docs/conf.py
> 
> For MkDocs projects:
> 
> version: 2
> mkdocs:
>   configuration: mkdocs.yml
> 
> Note: If you're using build.commands, no changes are required.

## TODOs

The email explicitly mentions the nextstrain-cli project, but looks like most of our repos do not specify the Sphinx configuration

- [x] https://github.com/nextstrain/augur/pull/1701
- [x] https://github.com/nextstrain/auspice/pull/1923
- [x] https://github.com/nextstrain/cli/pull/410
- [x] https://github.com/nextstrain/docs.nextstrain.org/pull/240
- [x] https://github.com/nextstrain/ncov/pull/1166
- [x] https://github.com/nextstrain/sphinx-theme/pull/53
