### ISSUE TITLE
Support Snakemake version 8 across core pathogen workflows

### ISSUE THREAD

**Issue by victorlin** [nextstrain/public#4]
Currently, our managed runtimes come with Snakemake version 7 so our core pathogen workflows have been written to work with that.

Snakemake [version 8](https://github.com/snakemake/snakemake/releases/tag/v8.0.0) was released in December 2023.

It's known to not work in ncov, [reported](https://github.com/nextstrain/ncov/issues/1114) by an external user. Not sure about other repos as we haven't tried yet.

## Tasks

- [x] create docker-base image to simplify testing of compatibility: [`docker.io/nextstrain/base:branch-victorlin-install-snakemake-8`](https://github.com/nextstrain/docker-base/pull/231)
- [ ] Update ncov to be compatible with version 8
- [ ] https://github.com/nextstrain/ncov-ingest/issues/452
- [ ] _add other pathogen repos_
- [ ] Bump Snakemake version in managed runtimes

**Comment by corneliusroemer** [comment]
Thanks so much for the effort @joverlee521! Greatly appreciated!
