### ISSUE TITLE
Standardize on `main` as default branch name

### ISSUE THREAD

**Issue by genehack** [nextstrain/public#8]
## todo

- [x] @genehack to replace this with a comprehensive list of repos that need to updated
- [ ] [.github](https://github.com/nextstrain/.github)
- [ ] [auctor](https://github.com/nextstrain/auctor)
- [ ] [auspice](https://github.com/nextstrain/auspice)
- [ ] [auspice.us](https://github.com/nextstrain/auspice.us)
- [ ] [avian-flu](https://github.com/nextstrain/avian-flu)
- [ ] [cli](https://github.com/nextstrain/cli)
- [ ] [community-search](https://github.com/nextstrain/community-search)
- [ ] [community-test](https://github.com/nextstrain/community-test)
- [ ] [conda](https://github.com/nextstrain/conda)
- [ ] [conda-base](https://github.com/nextstrain/conda-base)
- [ ] [cov](https://github.com/nextstrain/cov)
- [ ] [docker-base](https://github.com/nextstrain/docker-base)
- [ ] [docs.nextstrain.org](https://github.com/nextstrain/docs.nextstrain.org)
- [ ] [ebola](https://github.com/nextstrain/ebola)
- [ ] [enterovirus_d68](https://github.com/nextstrain/enterovirus_d68)
- [ ] [fauna](https://github.com/nextstrain/fauna)
- [ ] [flora](https://github.com/nextstrain/flora)
- [ ] [flu_frequencies](https://github.com/nextstrain/flu_frequencies)
- [ ] [gisaid-dupes](https://github.com/nextstrain/gisaid-dupes)
- [ ] [hbv](https://github.com/nextstrain/hbv)
- [ ] [mers](https://github.com/nextstrain/mers)
- [ ] [mers-beast-tutorial](https://github.com/nextstrain/mers-beast-tutorial)
- [ ] [mpox](https://github.com/nextstrain/mpox)
- [ ] [mumps](https://github.com/nextstrain/mumps)

## has issue created
- [ ] [augur](https://github.com/nextstrain/augur/issues/1686)
- [ ] [narratives](https://github.com/nextstrain/narratives/issues/13)
- [ ] [ncov](https://github.com/nextstrain/ncov/issues/1116)
- [ ] [ncov-clades-schema](https://github.com/nextstrain/ncov-clades-schema/issues/22)
- [ ] [ncov-ingest](https://github.com/nextstrain/ncov-ingest/issues/449)
- [ ] [nextclade](https://github.com/nextstrain/nextclade/issues/1488)
- [ ] [nextclade_data](https://github.com/nextstrain/nextclade_data/issues/211)
- [ ] [nextfrequencies](https://github.com/nextstrain/nextfrequencies/issues/2)
- [ ] [nextstrain.org](https://github.com/nextstrain/nextstrain.org/issues/918)
- [ ] [phyloTree](https://github.com/nextstrain/phyloTree/issues/3)
- [ ] [rsv](https://github.com/nextstrain/rsv/issues/63)
- [ ] [sacra](https://github.com/nextstrain/sacra/issues/24)
- [ ] [seasonal-flu](https://github.com/nextstrain/seasonal-flu/issues/169)
- [ ] [spheres-augur-build](https://github.com/nextstrain/spheres-augur-build/issues/1)
- [ ] [tb](https://github.com/nextstrain/tb/issues/10)
- [ ] [translations](https://github.com/nextstrain/translations/issues/242)
- [ ] [whitepaper](https://github.com/nextstrain/whitepaper/issues/1)
- [ ] [zika-tutorial](https://github.com/nextstrain/zika-tutorial/issues/14)

## `master` renamed to `main`
- [x] [workflow-asset-summary](https://github.com/nextstrain/workflow-asset-summary/issues/7)
- [x] [yellow-fever](https://github.com/nextstrain/yellow-fever/issues/4)
- [x] [lassa](https://github.com/nextstrain/lassa/issues/7)
- [x] [zika-tutorial-nextflow](https://github.com/nextstrain/zika-tutorial-nextflow/issues/6)

**Comment by victorlin** [comment]
As a follow-up to https://github.com/nextstrain/ebola/pull/32, I've updated the issue description with a list of things to check. If there are things that other people have done when applying the rename to other repos, please add them.
